version: '3.9'

services:
  # Database Service
  db:
    image: postgres:14
    container_name: our_postgres
    environment:
      POSTGRES_USER: yassine
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: our_backenddatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data:
