version: '3.8'
services:
  db:
    image: postgres:14
    container_name: our_postgres
    environment:
      POSTGRES_USER: yassine
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: our_backenddatabase
    ports:
      - "5432:5432"  
    volumes:
      - db-data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yassine -d our_backenddatabase || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  flyway:
    image: flyway/flyway:9.16.0
    container_name: our_flyway
    depends_on:
      db:
        condition: service_healthy
    command: ["migrate"] 
    volumes:
      - ./backend/flyway/flyway.conf:/flyway/conf/flyway.conf
      - ./backend/sql:/flyway/sql
  
volumes:
  db-data:
